import sql from "mssql";

// Parámetros de conexión
const config = {
  user: "consulta", // tu nombre de usuario
  password: "seven7.8", // tu contraseña
  server: "10.158.23.231", // dirección del servidor
  database: "seven", // nombre de la base de datos
  options: {
    encrypt: true, // Si estás usando SQL Azure, sino lo puedes poner en false
    trustServerCertificate: true, // Lo puedes poner en true para evitar problemas con certificados
  },
};

// Consulta SQL
const query = `
SELECT 

    TIPO,
    NUM_CONTRATO,
	CODIGO,
	RUBRO,
	NOMBRE,
	CLIENTE,
    CON_INTERADMINISTRATIVO,
    NOMBRE_INTERADMINISTRATIVO,
	TIPOLOGÍA, 
	AÑO,
	ESTADO,
	FECHA_CONTRATO,
	PLAZO,
    TIPO_PLAZO,
    PRORROGA_DIAS,
	--REDUCCIONES 
	TOTAL_DIAS, 
    SUPERVISOR,
	FECHA_INI_CONTRATO,
    FECHA_FINAL_CONTRATO,
    FECHA_REAL_FINI,
    FECHA_COMPETENCIA,
   	TIPO_CONTRATO,
    VALTOTAL,
    PAGO_TOTAL
	,[SOCIAL Y REASENTAMIENTO] AS [SOCIAL Y REASENTAMIENTO]
	,[COMPONENTE PRUEBA] AS [COMPONENTE PRUEBA]
	,[PERSONAL] AS [PERSONAL]
	,[DISENOS Y ESTUDIOS] AS [DISENOS Y ESTUDIOS]
	,[EJECUCION] AS [EJECUCION]
	,[SOCIAL Y CCIONES] AS [SOCIAL Y CCIONES]
	,[APOYO LOGISTICO] AS [APOYO LOGISTICO]
	,[COMPRA DE PREDIOS] AS [COMPRA DE PREDIOS]
	,[ADMINISTRACION EDU] AS [ADMINISTRACION EDU]
	,[HONORARIOS DISENO] AS [HONORARIOS DISENO]
	,[JURIDICO] AS [JURIDICO]
	,[GENERAL] AS [GENERAL]
	,[COMPONENTE DE GESTION COMPRA PREDIOS] AS [COMPONENTE DE GESTION COMPRA PREDIOS]
	,[R-ENOVACION] AS [R-ENOVACION] 
	,[GRAVAMEN AL MOVIMIENTO FINANCIERO] AS [GRAVAMEN AL MOVIMIENTO FINANCIERO]
	,[OBLIGACIONES URBANISTICAS] AS [OBLIGACIONES URBANISTICAS]
	,[COSTOS DE GERENCIA] AS [COSTOS DE GERENCIA] 
	,[GRAVAMEN A LOS RENDIMIENTOS  FINANCIEROS] AS [GRAVAMEN A LOS RENDIMIENTOS  FINANCIEROS]
	,[POLIZAS] AS [POLIZAS]
	,[COSTOS NO OPERATIVOS] AS [COSTOS NO OPERATIVOS]
	,APOYO
    ,ENCARGADO_CLIENTE

	FROM (
		SELECT DISTINCT
		A.TOP_CODI AS TIPO,
		A.CON_NUME AS NUM_CONTRATO,
		CONCAT(A.CON_NUME, '-', A.TOP_CODI, '-', A.CON_ANOP  )AS CODIGO,
		G.RUB_CODI AS RUBRO,
		J.RUB_NOMB AS NOMBRE,
		D.TER_NOCO AS CLIENTE,
		I.ARB_CODI AS CON_INTERADMINISTRATIVO,
		I.ARB_NOMB AS NOMBRE_INTERADMINISTRATIVO,
		E.VAL_AN07 AS TIPOLOGÍA, 
		
		A.CON_ANOP AS AÑO,
		CASE
		WHEN A.CON_ESTA= 'M' THEN 'MINUTA'
		WHEN A.CON_ESTA= 'L' THEN 'IMPUESTOS'
		WHEN A.CON_ESTA= 'A' THEN 'ACTIVO'
		WHEN A.CON_ESTA= 'S' THEN 'SUSPENDIDO'
		WHEN A.CON_ESTA= 'N' THEN 'ANULADO'
		WHEN A.CON_ESTA= 'F' THEN 'FACTURADO'
		ELSE 'LIQUIDADO' END AS ESTADO,
		A.CON_FECH AS FECHA_CONTRATO,
		A.CON_PLAZ AS PLAZO,
		CASE WHEN  A.CON_UPLA ='H' THEN 'HORAS'
		WHEN  A.CON_UPLA ='D' THEN 'DIAS'
		WHEN  A.CON_UPLA ='S' THEN 'SEMANAS'
		WHEN  A.CON_UPLA ='M' THEN 'MESES'
		ELSE 'AÑOS' END AS TIPO_PLAZO,
		A.CON_PLTP AS PRORROGA_DIAS,
		
		A.CON_PLAT AS TOTAL_DIAS, 
		C.TER_NOCO AS SUPERVISOR,
		
		A.CON_FINI AS FECHA_INI_CONTRATO,
		A.CON_FEFI AS FECHA_FINAL_CONTRATO,
		A.CON_FFIN AS FECHA_REAL_FINI,
		DATEADD(MONTH, 6, DATEADD(YEAR, 2, A.CON_FFIN)) AS FECHA_COMPETENCIA,
		B.TPC_NOMB AS TIPO_CONTRATO,
		COALESCE(F.VALTOTAL, 0) AS VALTOTAL,
		COALESCE(F.PAGO_TOTAL, 0) AS PAGO_TOTAL,
		M.DPR_PORC, N.COM_NOMB,
		P.TER_NOCO AS APOYO, 
        Q.TER_NOCO AS ENCARGADO_CLIENTE

		 FROM CT_CONTR A
				LEFT JOIN GN_VALPE E ON  A.EMP_CODI = E.EMP_CODI AND A.CON_CONT = E.VAL_ORIG --AND E.PRO_CODI ='SCTCONTR'
				INNER JOIN CT_DDISP H ON A.EMP_CODI = H.EMP_CODI AND A.CON_CONT = H.CON_CONT AND H.TAR_CODI = 3
				INNER JOIN GN_ARBOL I ON H.EMP_CODI = I.EMP_CODI AND H.ARB_CONT = I.ARB_CONT 
				INNER JOIN CT_TPCTR B ON A.EMP_CODI = B.EMP_CODI AND A.TPC_CONT = B.TPC_CONT
				INNER JOIN GN_TERCE C ON A.EMP_CODI = C.EMP_CODI AND A.CON_COOR = C.TER_CODI
				INNER JOIN GN_TERCE D ON A.EMP_CODI = D.EMP_CODI AND A.TER_CODI = D.TER_CODI
				LEFT JOIN V_CT_HIS F ON A.EMP_CODI = F.EMP_CODI AND A.CON_NUME = F.CON_NUME 
				AND A.TOP_CODI = F.TOP_CODI AND A.CON_ANOP = F.CON_ANOP
				INNER JOIN CT_DRDOC G ON  A.EMP_CODI = G.EMP_CODI AND A.CON_CONT = G.CON_CONT
				INNER JOIN PG_RUBRO J ON G.EMP_CODI = H.EMP_CODI AND G.RUB_CONT = J.RUB_CONT
				INNER JOIN CV_CONVE K ON K.EMP_CODI = E.EMP_CODI AND K.CON_CONT = E.VAL_NU02
				INNER JOIN CV_PROYE L ON K.EMP_CODI = L.EMP_CODI AND K.CON_CONT = L.CON_CONT
				INNER JOIN CV_DPROY M ON L.EMP_CODI = M.EMP_CODI AND L.PRO_CONT = M.PRO_CONT
				INNER JOIN CV_COMPO N ON M.EMP_CODI = N.EMP_CODI AND  M.COM_CONT = N.COM_CONT
				INNER JOIN GN_TERCE O ON A.EMP_CODI = O.EMP_CODI AND A.TER_SUP1 = O.TER_CODI
				INNER JOIN GN_TERCE P ON A.EMP_CODI = P.EMP_CODI AND A.TER_INT1 = P.TER_CODI
				INNER JOIN GN_TERCE Q ON A.EMP_CODI = Q.EMP_CODI AND A.TER_INT2 = Q.TER_CODI

		WHERE 

	 A.CON_ESTA = 'A'
	 AND A.TOP_CODI IN (3302, 3306, 3322, 3325, 3326, 3327, 3399)
	 
	  
 ) TablaPivote
  PIVOT ( SUM  (DPR_PORC) 
		FOR COM_NOMB IN
    ( 
	[SOCIAL Y REASENTAMIENTO]	,[COMPONENTE PRUEBA] 	,[PERSONAL] 	,[DISENOS Y ESTUDIOS] 	,[EJECUCION] 	,[SOCIAL Y CCIONES] 	,[APOYO LOGISTICO]
	,[COMPRA DE PREDIOS] 	,[ADMINISTRACION EDU] 	,[HONORARIOS DISENO] 	,[JURIDICO]	,[GENERAL] 	,[COMPONENTE DE GESTION COMPRA PREDIOS] 
	,[R-ENOVACION]	,[GRAVAMEN AL MOVIMIENTO FINANCIERO] 	,[OBLIGACIONES URBANISTICAS] 	,[COSTOS DE GERENCIA]	,[GRAVAMEN A LOS RENDIMIENTOS  FINANCIEROS] 
	,[POLIZAS] 	,[COSTOS NO OPERATIVOS]
	)
	) AS PivotTable

	order by 
	 NUM_CONTRATO,
	 AÑO,
	 RUBRO
`;

async function executeQuery() {
  try {
    // Conectar al servidor SQL
    await sql.connect(config);

    // Ejecutar la consulta SQL
    const result = await sql.query(query);

    // Mostrar los resultados en consola
    console.log(result.recordset.map((rec)=>rec));

    // Cerrar la conexión
    sql.close();
  } catch (err) {
    console.error("Error ejecutando la consulta:", err);
  }
}

// Ejecutar la consulta
executeQuery();
