SELECT  
		A.CON_NCON AS [CONTRATO INTERADMINISTRATIVO]
		,B.CLI_NOCO AS CLIENTE 
		,C.VAL_AN02 AS ESTADO
		,A.CON_OBJE AS OBJETO
		,A.CON_FECH AS [FECHA SUSCRIPCIÓN]
		,A.CON_FECA AS [FECHA ACTA DE INICIO]
		,A.CON_FECM AS  [FECHA MINUTA]
		,A.CON_FETE AS [FECHA TERMINACIÓN]
		,A.CON_PLAZ  AS PLAZO
		,A.CON_VALH AS [VALOR HONORARIOS]
		,A.CON_VALP AS VALOR
		,A.CON_PORH AS [PORCENTAJE HONORARIOS]
		,C.VAL_AN08 AS [% HONORARIOS PREDIOS]
		,G.TER_CODA AS [DOC COORDINADOR]
		,G.TER_NOCO AS COORDINADOR
		,H.TER_CODA AS [DOC PMP]
		,H.TER_NOCO AS PMP 
		,I.TER_CODA AS [DOC ADMINISTRATIVO]
		,I.TER_NOCO AS ADMINISTRATIVO
		,A.CON_CCLI AS [CENTRO DE COSTOS]
		, L.RUB_CODI AS RUBRO
		, L.RUB_NOMB AS [NOMBRE RUBRO]
		, M.COD_PROY AS PROYECTO
		,D.PRO_NOMB AS [NOMBRE DE PROYECTO]
		, M.COD_COMP AS COMPONENTE
		,L.COM_NOMB AS [NOMBRE COMPONENTE]
		,L.RUB_FUEN as [FUENTE]
		,L.FUE_NOMB AS [NOMBRE FUENTE]
		, M.APROPIADO AS APROPIADO
		, M.CDP AS CDP
		, M.DISPONIBLE AS DISPONIBLE
		, M.COMPR AS COMPROMETIDO
		, M.PAGOS AS PAGOS
		, M.POR_COMPROMETER AS [POR COMPROMETER]
		, M.POR_PAGAR AS [POR PAGAR]	
	
		FROM CV_CONVE A
			INNER JOIN FA_CLIEN B ON A.EMP_CODI = B.EMP_CODI AND A.CLI_CODI = B.CLI_CODI
			INNER JOIN GN_VALPE C ON A.EMP_CODI = C.EMP_CODI AND A.CON_CONT = C.VAL_ORIG
			INNER JOIN CV_PROYE D ON A.EMP_CODI = D.EMP_CODI AND A.CON_CONT = D.CON_CONT
			INNER JOIN GN_VALPE E ON A.EMP_CODI = E.EMP_CODI AND A.CON_CONT = E.VAL_ORIG
			INNER JOIN EDU_RUBR L ON A.EMP_CODI = L.EMP_CODI AND A.CON_CCLI = L.RUB_CONV
			INNER JOIN PANEL_CV_TOTAL_DET M ON L.RUB_CONV = M.COD_CONV  AND L.RUB_PROY = M.COD_PROY  AND L.RUB_COMP =M.COD_COMP
			full JOIN GN_TERCE G ON C.EMP_CODI = G.EMP_CODI AND C.VAL_AN05 = G.TER_CODA
			full JOIN GN_TERCE H ON C.EMP_CODI = H.EMP_CODI AND C.VAL_AN06 = H.TER_CODA
			full JOIN GN_TERCE I ON C.EMP_CODI = I.EMP_CODI AND C.VAL_AN06 = I.TER_CODA
	
			
			
	WHERE A.CON_ANOP >= 2021
	--AND A.CON_NUME in ( 518, 437, 513 )
	
	ORDER BY [CONTRATO INTERADMINISTRATIVO],[FECHA SUSCRIPCIÓN]

	