SELECT  
		A.CON_NCON AS [CONT_INTERADMINISTRATIVO]
		,A.CON_NOMB AS [NOMBRE_INTERADMINISTRATIVO]
		,B.CLI_NOCO AS CLIENTE 
		,C.VAL_AN02 AS ESTADO
		,A.CON_OBJE AS OBJETO
		,A.CON_FECH AS [FECHA_SUSCRIPCIÓN]
		,A.CON_FECA AS [FECHA_ACTA_DE_INICIO]
		,A.CON_FECM AS  [FECHA_MINUTA]
		,A.CON_FETE AS [FECHA_TERMINACIÓN]
		,A.CON_PLAZ  AS PLAZO
		,A.CON_VALH AS [VALOR_HONORARIOS]
		,A.CON_VALP AS VALOR
		,A.CON_PORH AS [PORCENTAJE_HONORARIOS]
		,C.VAL_AN08 AS [%_HONORARIOS_PREDIOS]
		,G.TER_CODA AS [DOC_COORDINADOR]
		,G.TER_NOCO AS COORDINADOR
		,H.TER_CODA AS [DOC_PMP]
		,H.TER_NOCO AS PMP 
		,I.TER_CODA AS [DOC_ADMINISTRATIVO]
		,I.TER_NOCO AS ADMINISTRATIVO
		,A.CON_CCLI AS [CENTRO_DE_COSTOS]
	
		FROM CV_CONVE A
			INNER JOIN FA_CLIEN B ON A.EMP_CODI = B.EMP_CODI AND A.CLI_CODI = B.CLI_CODI
			INNER JOIN GN_VALPE C ON A.EMP_CODI = C.EMP_CODI AND A.CON_CONT = C.VAL_ORIG
			
			full JOIN GN_TERCE G ON C.EMP_CODI = G.EMP_CODI AND C.VAL_AN05 = G.TER_CODA
			full JOIN GN_TERCE H ON C.EMP_CODI = H.EMP_CODI AND C.VAL_AN06 = H.TER_CODA
			full JOIN GN_TERCE I ON C.EMP_CODI = I.EMP_CODI AND C.VAL_AN06 = I.TER_CODA
	
			
			
	WHERE A.CON_ANOP >= 2010
	AND A.CON_ETAP = 'C'
	     
	
	
	ORDER BY [CONTRATO_INTERADMINISTRATIVO],[FECHA_SUSCRIPCIÓN]
	
